#!/usr/bin/env bash

TEMPLATES_DIR="$(xdg-user-dir TEMPLATES)"

template=$(find "${TEMPLATES_DIR}/" -mindepth 1 -maxdepth 1 -type f -print0 |
  sort --zero-terminated --reverse --ignore-case --dictionary-order |
  xargs -0 -n1 basename |
  fzf)

if [ -z "$template" ]; then
  printf "No template selection. Exiting."
  exit
fi

ext="${template##*.}"

read -r -p "Filename: " outstem

if [ -z "$outstem" ]; then
  printf "No name for the new file. Exiting."
  exit
fi

outfile="$outstem"."$ext"

if [ -f "$outfile" ]; then
	echo -e "\e[1m\e[31mERROR:\e[0m\e[31m File \"$outfile\" already exist\e[0m"
	exit 1
fi

cp "${TEMPLATES_DIR}/${template}" "${outfile}"
